translate_multilingual<-function(){
library(data.table)
library(stringr)
library(plyr)
library(tidyr)
library(lubridate)
library(splitstackshape)
library(anytime)
library(broman)
x <- readline("What is the path to the files you want to translate?")
x <- gsub("\\", "/",x, fixed=TRUE)
setwd(x)

#Formatting functions
myformatter<-function(txt){
  #extract numbers of list
  vec1 <- str_extract_all(txt,"[0-9]+")[[1]] #Extract numbers
  #extract text: first, break it with |
  #then, extract numbers and comma
  vec2<-str_split(txt,"\\|")
  vec2<-gsub("^\\d+,|[ ]+\\d+,", "",vec2[[1]])
  #vec2 <- str_extract_all(txt,'(?<=([0-9][ ]{0,4},))[\\w \\"]+')[[1]] #Extract text
  #vec2 <- gsub("^[ ]+|[ ]+$","",vec2)   #Remove spaces
  res<-paste0("\"",vec1,"\":\"",vec2,"\"",collapse = ",")
  return(res)
}
lang<-strsplit(readline("Insert the languages in the order that you want them displayed in the form (i.e. Fran?ais English Deutsch)
               You will need a csv file containing the translations for each language:")," ")[[1]]

# Creating the action tags that will generate the translations in redcap ---------------------------------------
#Open each language data dictionnary
#The columns that contain text to be translated are:
# Section Header --column 3
# Field Label --column 5
# Choices, Calculations, OR Slider Labels --column 6
# Field Note --column 7
l<-list()
qhea<-list()
qcol<-list()
qans<-list()
qnot<-list()
for(i in seq(lang)){
  print(paste0("Language \"",lang[i],"\""))
  l[[i]]<-fread(readline("Enter file name with extension: "),header = F, encoding = "unknown")
  qhea[[i]]<-as.data.table(l[[i]])[,V3] #Headers
  qcol[[i]]<-as.data.table(l[[i]])[,V5] #Questions
  qans[[i]]<-as.data.table(l[[i]])[,V6] #Answers
  qnot[[i]]<-as.data.table(l[[i]])[,V7] #Field notes
}
#Capturing first line as the headers (as they are separated by spaces it is easier to deal with Vx rather than the names present in the file)
prim<-as.data.table(l[1]) #primary language data dictionnary
myheaders<-prim[1]
mysubjectid<-prim[2]

#Vector that contains the column names of the questions for each language (column V5 is always the question column but the number of files
#to treat changes according to the number of languages defined)
#Creating empty temporary columns
prim[,c(paste0("tmp",1:4)):=""]

#Modifying values of column "Field Annotation". There is where we store the translations.
for(i in 2:nrow(prim)){ #Skipping first row as it contains the languages variable
  #Headers: attaching all text in primary file header column
  if(prim[i,V3]!=""){
    prim[i,V3:= paste0(toupper(substr(lang, start = 1, stop = 2)),": ",sapply(qhea, function(x)x[i]),collapse="\n\n")]
  }
  #question texts: temporary column tmp1
  prim[i,"tmp1":= paste0("\"",lang,"\": \"",sapply(qcol, function(x)x[i]),"\"",collapse=",")]

  #answers: temporary column tmp2
  if(prim[i,V4] %in% c("radio","checkbox","dropdown","yesno")){
    prim[i,"tmp2":= paste0("\"",lang,"\":{",sapply(qans, function(x)myformatter(x[i])),"}",collapse=",")]

      }
  # Do not use yesno fields, only radio because they will need to be translated as a radio button anyways.
  # #Third part: error messages
  # #Not included yet

  #Fourth part: field notes. Not tested
  # if(prim[i,V7]!=""){
  #   prim[i,"tmp4":= paste0("\"",lang,"\":{",sapply(qnot, function(x)x[i]),"}",collapse=",")]
  # }
}
#Pasting all of them together in the "Field Annotation" column
#Needs modification when adding error messages
prim[,"V18":=paste0(ifelse(tmp1!="",paste0("@p1000lang{",tmp1,"} "),""),
                       ifelse(tmp2!="",paste0("@p1000answers{",tmp2,"} "),""),
                       ifelse(tmp4!="",paste0("@p1000notes{",tmp4,"}"),""))]

#Examples of questions, answers, errors and notes in data dictionnary generated by redcap
#@p1000lang{"English":"My second question","Fran?ais":"Ma deuxi?me question","Deutsch":"Meine zweite Frage"}
#@p1000answers{"English":{"1":"My second choice 1","2":"My second choice 2","3":"My second choice 3"},"Fran?ais":{"1":"mon choix 1","2":"mon choix 2
#@p1000notes{""English"":""my little note"",""Fran?ais"":""ma petite note"",""Deutsch"":""meine kleine note""}"
#@p1000errors{""English"":""english error"",""Fran?ais"":""francais error"",""Deutsch"":""deutsch error""}

#Suppressing temporary columns
prim[,c(paste0("tmp",1:4)):=NULL]
#Adding missing lines: language variable and headers
#mytable<-rbind(myheaders,mytable)
langrow<-as.data.table(t(c("languages",mysubjectid[,V2],"","dropdown","languages",paste0(seq(lang),", ",lang,collapse=" | "),"","","","","","","","","","","","@HIDDEN")))
prim<-rbind(langrow,prim[3:nrow(prim)])
#Adding headers back again
prim<-rbind(mysubjectid,prim)
prim<-rbind(myheaders,prim)

#Changing encoding to utf8
# encode<-function(x){x<-enc2utf8(x)
# Encoding(x) <- "unknown"}
# prim[,(names(prim)):=lapply(.SD,encode)]



#Writing files
fwrite(prim, file=paste0("translations_",Sys.Date(),".csv"),col.names = F)
}

